image:
  registry: ""
  pullPolicy: "IfNotPresent"

services:
  ui:
    enabled: true
    repository: ui
    tag: dev
    port: 3000
    replicas: 1
  server:
    enabled: true
    repository: server
    tag: dev
    port: 5329
    replicas: 1
  jobs:
    enabled: false
  nsfwDetector:
    enabled: false

# Disable all operators and additional services for minimal deployment
pgoPostgresql:
  enabled: false
spotahomeRedis:
  enabled: false
vso:
  enabled: false
adminer:
  enabled: false

ingress:
  enabled: false

config:
  env: "development"