{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vrooli.fullname" . }}-ingress
  labels:
    {{- include "vrooli.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ $.Values.productionDomain | default .host }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "vrooli.fullname" $ }}-{{ .service }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ $.Values.tlsSecretName | default .secretName }}
      hosts:
      {{- range .hosts }}
        - {{ $.Values.productionDomain | default . }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }} 