analyzed_at: null
attempts:
    - error: exit status 1
      timestamp: "2025-09-05T00:18:54-04:00"
blockers: []
completed_at: null
created_at: 2025-09-05T00:18:35.43191763-04:00
created_by: human
dependencies: []
description: say hello
error: exit status 1
failed_at: "2025-09-05T00:18:54-04:00"
id: task-5a99b2c5
notes: ""
priority_estimates: {}
priority_score: null
started_at: null
status: ""
target: ""
title: test
type: feature
