analyzed_at: null
attempts:
    - error: exit status 1
      timestamp: "2025-09-04T21:55:03-04:00"
blockers: []
completed_at: null
created_at: 2025-09-04T21:54:44.772139288-04:00
created_by: human
dependencies: []
description: If you see this, say hello!
error: exit status 1
failed_at: "2025-09-04T21:55:03-04:00"
id: task-ed3c1d73
notes: ""
priority_estimates: {}
priority_score: null
started_at: null
status: ""
target: ""
title: test
type: testing
